[workspace]
members = ["pkgs/app", "pkgs/metallic"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0"
pollster = "0.3"
wgpu = "0.20"
winit = "0.30"

[workspace.dependencies.bytemuck]
version = "1.16"
features = ["derive"]

[profile.release]
opt-level = "s"
