[package]
name = "metallic"
version = "0.1.0"
edition = "2021"

[dependencies.bytemuck]
workspace = true

[dependencies.pollster]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.winit]
workspace = true

[dependencies.wgpu]
workspace = true
